# Soal 8

1. [hitung PVE dengan menggunakan sdev](#1)
2. [gunakan persamaan 10.8](#2)

## 1

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

%matplotlib inline

In [9]:
arrest = pd.read_csv('../dataset/USArrests.csv')

In [10]:
arrest.head(10)

Murder  Assault  UrbanPop  Rape        State
0    13.2      236        58  21.2      Alabama
1    10.0      263        48  44.5       Alaska
2     8.1      294        80  31.0      Arizona
3     8.8      190        50  19.5     Arkansas
4     9.0      276        91  40.6   California
5     7.9      204        78  38.7     Colorado
6     3.3      110        77  11.1  Connecticut
7     5.9      238        72  15.8     Delaware
8    15.4      335        80  31.9      Florida
9    17.4      211        60  25.8      Georgia

In [11]:
arrest = arrest = pd.read_csv('../dataset/USArrests.csv', index_col=4)

In [12]:
arrest.head()

Murder  Assault  UrbanPop  Rape
State                                      
Alabama       13.2      236        58  21.2
Alaska        10.0      263        48  44.5
Arizona        8.1      294        80  31.0
Arkansas       8.8      190        50  19.5
California     9.0      276        91  40.6

In [13]:
arrest.shape

(50, 4)

In [14]:
arrest.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, Alabama to Wyoming
Data columns (total 4 columns):
Murder      50 non-null float64
Assault     50 non-null int64
UrbanPop    50 non-null int64
Rape        50 non-null float64
dtypes: float64(2), int64(2)
memory usage: 2.0+ KB


In [15]:
scl = StandardScaler()
arrest_scl = scl.fit_transform(arrest)

/home/uulwake/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/home/uulwake/anaconda3/lib/python3.7/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [21]:
arrest_scl

array([[ 1.25517927,  0.79078716, -0.52619514, -0.00345116],
       [ 0.51301858,  1.11805959, -1.22406668,  2.50942392],
       [ 0.07236067,  1.49381682,  1.00912225,  1.05346626],
       [ 0.23470832,  0.23321191, -1.08449238, -0.18679398],
       [ 0.28109336,  1.2756352 ,  1.77678094,  2.08881393],
       [ 0.02597562,  0.40290872,  0.86954794,  1.88390137],
       [-1.04088037, -0.73648418,  0.79976079, -1.09272319],
       [-0.43787481,  0.81502956,  0.45082502, -0.58583422],
       [ 1.76541475,  1.99078607,  1.00912225,  1.1505301 ],
       [ 2.22926518,  0.48775713, -0.38662083,  0.49265293],
       [-0.57702994, -1.51224105,  1.21848371, -0.11129987],
       [-1.20322802, -0.61527217, -0.80534376, -0.75839217],
       [ 0.60578867,  0.94836277,  1.21848371,  0.29852525],
       [-0.13637203, -0.70012057, -0.03768506, -0.0250209 ],
       [-1.29599811, -1.39102904, -0.5959823 , -1.07115345],
       [-0.41468229, -0.67587817,  0.03210209, -0.34856705],
       [ 0.44344101, -0.

In [22]:
PCA = PCA()
PCA.fit(arrest_scl)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [23]:
PCA.explained_variance_ratio_

array([0.62006039, 0.24744129, 0.0891408 , 0.04335752])

[kembali ke atas](#Soal-8)

## 2

In [24]:
PCA.components_

array([[ 0.53589947,  0.58318363,  0.27819087,  0.54343209],
       [ 0.41818087,  0.1879856 , -0.87280619, -0.16731864],
       [-0.34123273, -0.26814843, -0.37801579,  0.81777791],
       [ 0.6492278 , -0.74340748,  0.13387773,  0.08902432]])

In [27]:
for k in range(0,np.shape(PCA.components_)[1]):
    # Numerator
    accum = 0
    num = 0
    for i in range(0, np.shape(arrest_scl)[0]):
        for j in range(0, np.shape(arrest_scl)[1]):
            accum += PCA.components_[k][j] * arrest_scl[i][j]
        num += accum**2
        accum = 0

    # Denominator
    accum = 0
    den = 0
    for j in range(0, np.shape(arrest_scl)[1]):
        for i in range(0, np.shape(arrest_scl)[0]):
            accum += arrest_scl[i][j]**2
        den += accum
        accum = 0

    # Result
    print('principal component number:', k+1)
    print(num/den)

principal component number: 1
0.6200603947873732
principal component number: 2
0.24744128813496016
principal component number: 3
0.08914079514520745
principal component number: 4
0.0433575219324588


[kembali ke atas](#Soal-8)